[project]
name = "comfyui_soze"
description = "Nodes: Ultimate Concat (Mobile), Send Notification (Mobile), Settings Launcher (Mobile), Settings Launcher Outputs (Mobile)"
version = "1.0.0"
license = "LICENSE"
dependencies = ["requests"]

[project.urls]
Repository = "https://github.com/SozeInc/ComfyUI_Soze"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "soze"
DisplayName = "ComfyUI_Soze"
Icon = ""
